# название
name: Sent archive to server

# целевые события для запуска
# в данном случае это push и pull_request, в ветку master
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# выполняемые действия
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: ZIP SFTP Upload
        uses: sahil-io/release-upload-sftp@4.2
        with:
          package_name: 'instant_uploader'
          username: 'runcloud'
          server: '45.79.75.110'
          port: 22
          ssh_private_key: ${{ secrets.SSH_KEY }}
          local_path: './*'
          remote_path: '/home/runcloud/webapps/temp6localvisorcom/test/'
