# название
name: Project test & build

# целевые события для запуска
# в данном случае это push и pull_request, в ветку master
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# выполняемые действия
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    # запускаются по шагам
    # name - название шага
    # в github actions будет выводиться название шага, и процессы
    steps:
      #- name: Checkout
        #uses: actions/checkout@v2
        
      - name: deploy files to server
        uses: sahil-io/release-upload-sftp@4.2
        with:
          # в значение GITHUB_TOKEN помещается ссылка на ваш секрет в репозитории
          # в данном случае его название KEY
          GITHUB_TOKEN: ${{ secrets.TEST_SECRE_TOKEN_ACTION }}
          package_name: 'demo-package'
          username: 'runcloud'
          server: ${{ secrets.SERVER_IP }}
          port: 22
          ssh_private_key: ${{ secrets.ssh_key }}
          local_path: './*'
          remote_path: ${{ secrets.REMOTE_PATH}}
