# название
name: Test zip

# целевые события для запуска
# в данном случае это push и pull_request, в ветку master
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# выполняемые действия
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    # запускаются по шагам
    # name - название шага
    # в github actions будет выводиться название шага, и процессы
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - uses: papeloto/action-zip@v1
        with:
          files: /
          dest: result.zip

      - uses: actions/upload-artifact@v1
        with:
          name: my-artifact
          path: ${{ github.workspace }}/result.zip
